import { useTranslation } from 'react-i18next'
import { Area, AreaChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'
import { TrendingUp } from 'lucide-react'
import { useAppData } from '../data/AppDataContext'

const days = ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun']
function intensity(value) { if (value <= 2) return 'bg-surface-variant'; if (value <= 4) return 'bg-accent-container/30'; if (value <= 6) return 'bg-accent-container/60'; if (value <= 8) return 'bg-accent-container/90'; return 'bg-accent' }
function money(value) { return Number(value || 0).toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 }) }

export default function Dashboard() {
  const { t } = useTranslation()
  const { dashboard, loading, error } = useAppData()
  if (loading) return <div className="p-6 font-mono">Loading live dashboard…</div>
  if (error || !dashboard) return <div className="p-6 text-danger">{error || 'Dashboard data is unavailable.'}</div>
  const metric = (label, value, note) => <div className="bg-surface border border-border-warm p-4"><span className="font-mono text-xs font-bold uppercase text-text-warm">{label}</span><strong className="block text-3xl sm:text-4xl mt-2">{value}</strong><span className="mt-2 flex items-center gap-1 font-mono text-sm text-accent-light"><TrendingUp size={14}/>{note}</span></div>
  return <div className="min-h-full p-4 sm:p-6"><div className="grid grid-cols-1 sm:grid-cols-3 gap-4 mb-4">{metric(t('dashboard.revenue'), `${money(dashboard.totalRevenue)} DT`, `${dashboard.totalSales} completed sales`)}{metric(t('dashboard.avgTicket'), `${money(dashboard.averageTicket)} DT`, 'Based on completed sales')}{metric(t('dashboard.margin'), `${money(dashboard.margin)} DT (${dashboard.marginPct.toFixed(1)}%)`, 'Live gross margin')}</div><div className="grid grid-cols-1 lg:grid-cols-12 gap-4"><section className="lg:col-span-8 space-y-4"><div className="bg-surface border border-border-warm p-4 h-72"><h2 className="font-mono text-xs font-bold text-text-warm uppercase mb-4">{t('dashboard.trend')}</h2><ResponsiveContainer width="100%" height="90%"><AreaChart data={dashboard.revenueTrend}><defs><linearGradient id="liveRevenue" x1="0" x2="0" y1="0" y2="1"><stop offset="5%" stopColor="#ff6b00" stopOpacity=".3"/><stop offset="95%" stopColor="#ff6b00" stopOpacity="0"/></linearGradient></defs><CartesianGrid stroke="#5a4136" vertical={false}/><XAxis dataKey="day" stroke="#5c616c"/><YAxis stroke="#5c616c"/><Tooltip formatter={(value) => `${money(value)} DT`}/><Area dataKey="revenue" type="monotone" stroke="#ff5a1f" fill="url(#liveRevenue)"/></AreaChart></ResponsiveContainer></div><div className="bg-surface border border-border-warm p-4"><h2 className="font-mono text-xs font-bold text-text-warm uppercase mb-4">{t('dashboard.heatmap')}</h2><div className="grid grid-cols-8 gap-1 min-w-[480px]">{dashboard.heatmap.map((row) => <div key={row.time} className="contents"><div className="font-mono text-xs text-text-warm flex items-center justify-end pr-2">{row.time}</div>{days.map((day) => <div key={`${row.time}-${day}`} title={`${day}: ${row[day] || 0}`} className={`h-8 ${intensity(row[day] || 0)}`}/>)}</div>)}<div/>{days.map((day) => <div key={day} className="font-mono text-xs text-center text-text-warm">{day}</div>)}</div></div></section><section className="lg:col-span-4 space-y-4"><SalesList title={t('dashboard.best')} rows={dashboard.topSellers}/><SalesList title={t('dashboard.slow')} rows={dashboard.slowMovers}/></section></div></div>
}

function SalesList({ title, rows }) { return <div className="bg-surface border border-border-warm p-4"><h2 className="font-mono text-xs font-bold uppercase text-accent-light mb-4">{title}</h2>{rows.length ? <div className="space-y-3">{rows.map((item) => <div key={item.sku} className="flex justify-between gap-3 border-b border-surface-variant pb-2"><div className="min-w-0"><b className="block truncate">{item.name}</b><span className="font-mono text-xs text-text-warm">{item.sku}</span></div><span className="font-mono font-bold">{item.sold}</span></div>)}</div> : <p className="text-text-warm">No inventory data yet.</p>}</div> }
